name: seed_together
description: "SeedTogether neu 2025"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # iOS-Design-Icons
  cupertino_icons: ^1.0.8

  # ✅ Für Supabase: Authentifizierung, Datenbank, Storage, etc.
  supabase_flutter: ^2.8.4

  # ✅ Zum Laden von .env-Dateien (z. B. API-Keys ausblenden)
  flutter_dotenv: ^5.2.1

  # ✅ Für Profilbilder, Pflanzenuploads etc.
  image_picker: ^1.1.2

  # ✅ Zugriff auf Gerätespeicherpfade (z. B. temporäre Bilder speichern)
  path_provider: ^2.1.5

  # ✅ Kamerazugriff, Galerie-Zugriff etc. mit expliziter Berechtigungsabfrage
  permission_handler: ^11.3.1

  # ✅ Deep Linking: Für Passwort-Zurücksetzen & Routing
  app_links: ^6.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Gute Codequalität durch empfohlene Lint-Regeln
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
